name: NoJoinLeave
version: '${project.version}'
main: net.daechler.nojoinleave.NoJoinLeave
api-version: 1.19
authors: [ Daechler ]
description: This plugin disables the vanilla join and leave messages.
